=== nddat1908/T1908A_Sem2/XML/Lab02/ElectionSurvey_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    Document    : ElectionSurvey_schema.xsd
    Author      : vincent
    Description :
        This document defines a schema for collecting voter details.
-->

<xs:schema xmlns="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://www.electionsurvey.com"
           xmlns="http://www.electionsurvey.com"
           elementFormDefault="qualified">
    <xs:element name="VoterDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="VoterName" type="xs:string"/>
                <xs:element name="Gender" type="xs:string"/>
                <xs:element name="Age" type="xs:integer"/>
                <xs:element name="DateOfBirth" type="xs:date"/>
                <xs:element name="Profession" type="xs:string"/>
                <xs:element name="PhoneNumber" type="xs:long"/>
                <xs:element name="Address" type="xs:string"/>
                <xs:element name="City" type="xs:string"/>
                <xs:element name="State" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nddat1908/T1908A_Sem2/XML/Lab02/ElectionSurvey.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    Document    : ElectionSurvey_schema.xsd
    Author      : vincent
    Description :
        Purpose of the document follows.
-->

<VoterDetails xmlns="http://www.electionsurvey.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.electionsurvey.com ElectionSurvey_schema.xsd">
    <VoterName>Halle Brown</VoterName>
    <Gender>Female</Gender>
    <Age>24</Age>
    <DateOfBirth>1982-05-13</DateOfBirth>
    <Professtion>Student</Professtion>
    <PhoneNumber>04024162567</PhoneNumber>
    <Address>378-Park Street</Address>
    <City>4000 Stavanger</City>
<!--    <State>Bergen</State>-->
    <State>Noway</State>
</VoterDetails>
